// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM3Lf6X8beVqpBIjB3K4ZdjAUV7Z00f6w',
    appId: '1:683821103431:web:577f312b8689a634f1f462',
    messagingSenderId: '683821103431',
    projectId: 'portofoli-aa631',
    authDomain: 'portofoli-aa631.firebaseapp.com',
    storageBucket: 'portofoli-aa631.appspot.com',
    measurementId: 'G-2TLV0KH3EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Y5vqjD8rW7OcAd6YStfPIl0LB5a14DM',
    appId: '1:683821103431:android:8093bb42ea3a2341f1f462',
    messagingSenderId: '683821103431',
    projectId: 'portofoli-aa631',
    storageBucket: 'portofoli-aa631.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG8Qtwkb0sPR_wd4-pI9f62kUdAZPDRgE',
    appId: '1:683821103431:ios:97d18aca99e19215f1f462',
    messagingSenderId: '683821103431',
    projectId: 'portofoli-aa631',
    storageBucket: 'portofoli-aa631.appspot.com',
    iosClientId: '683821103431-dsrjj827dvbikf05ffiipt6grhsnedo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
